import { Inter } from "next/font/google"; // Use the Google font import
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/home/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
