import { Inter } from "next/font/google"; // Mengimpor font dari Google
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ReactNode } from "react"; // Mengimpor ReactNode

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Menentukan tipe untuk props
interface RootLayoutProps {
  children: ReactNode; // Menentukan tipe children
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
