import { Inter } from "next/font/google"; // Gunakan import font dari Google
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/home/Hero";
import { ReactNode } from "react"; // Import ReactNode

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Definisikan tipe untuk children
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
